[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[fmt]
line_length = 120

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
amoy = "${POLYGON_AMOY_TESTNET_RPC_URL}"
anvil = "${ANVIL_RPC_URL}"
op = "${OP_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
op = { key = "${ETHERSCAN_API_KEY}" }